### ISSUE TITLE
Running time?

### ISSUE THREAD

**Issue by antithing** [hjshxb/LiKL-cpp#1]
Hi, and thank you for making this code available. 
What is the frame time on a 512x512 image? 
Could this approach reach 50Hz?

Thanks!

**Comment by hjshxb** [comment]
> 

It's about 12 ms with a GTX 3060（640 x 480）, which includes getting keypoints and their descriptors; line segments and their descriptors.
Thank you for your attention.😊

**Comment by hjshxb** [comment]
Hi. I'll close this issue and create a new issue if there are any questions.

Thanks.
